### ISSUE TITLE
Language Guide TODO List

### ISSUE THREAD

**Issue by weileiming** [WeiLeiming/SwiftTutorial#1]
- [x] 基础部分 The Basics
- [x] 基本运算符 Basic Operators
- [x] 字符串和字符 Strings and Characters
- [x] 集合类型 Collection Types
- [x] 控制流 Control Flow
- [x] 函数 Functions
- [x] 闭包 Closures
- [x] 枚举 Enumerations
- [x] 类和结构体 Classes and Structures
- [x] 属性 Properties
- [x] 方法 Methods
- [x] 下标 Subscripts
- [x] 继承 Inheritance
- [x] 构造过程 Initialization
- [x] 析构过程 Deinitialization
- [x] 自动引用计数 Automatic Reference Counting
- [x] 可选链 Optional Chaining
- [x] 错误处理 Error Handling
- [x] 类型转换 Type Casting
- [x] 嵌套类型 Nested Types
- [x] 扩展 Extensions
- [x] 协议 Protocols
- [x] 泛型 Generics
- [x] 访问控制 Access Control
- [x] 高级运算符 Advanced Operators
